### PR TITLE
A few tests added including failed test on Seek(End)

### PR DESCRIPTION
**Pull request by xkrt**

### CODE REVIEW

**Comment by xkrt** [comment]
Do you have idea how to fix the test?

**Comment by lassevk** [comment]
I'll get around to it, busy week unfortunately.

**Comment by lassevk** [comment]
I think my push yesterday or so fixed it, the tests go green at least. I should add a lot more tests to verify all the functionality though.

**Comment by xkrt** [comment]
Yeah, its works for me, cant find any issues. Thanks!

**Pull request merged**
